language: node_js
node_js:
- 'lts/*'
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: hGjdQaBdTRNM3IkKRDU0IuFUrL27CN6dHf79a02M3LrVQTk5zWiovCWsL+1ixaUiea9wYFGhMtbsp74tCb84QrOZTGB3L3uNuk6PrDccLTkPF0QITW1KDO14QK1has1OhCezTuekjNNf4cUPEmfruT/j7v+5H+UnD2uaUyyg6MD9D6sjD358aMNh+HJZjfUG8KcCSj8vsk/Cp+RmvWbz0V4CCBMRkIh1yFR+fOH8GCzGAQUzzrSEIopyQg2U0xI+Hm3dtKvhnUCkPsEfQS0GyPii3Jl7AKIaqUx4FAFQBRS8IHt47c4g0R8Q3OlA+UpuBWeBvgRh8709ExGCMm65LXuoruLtxi/8jTbJO/5lyAHK9zm/1RgC5ZCwYj8sfhRbKeSOIGiZPpN+82aTgyW3YvWIXTxvKBWI9KCeEtJA3sSZzNJvQ7zCQJbKxb9RRw38DCvVGYDyn9bqZxGcUafMu7++IrzWrK9gtmx+LzyBj1E8I99ih3c/bJqHiBgvs9v1NBJdRVxUvlCP6jXrVXb3DRR1jvbYfsN6DjAx1PrwBZNckr3/0H79hPrcbHlOp7QGunRV7D9k2bopHxe4AYCc1eOMiqzh2EdS7n6uOAj0WcxwUeF6UpSBCxLUV9h2gBoJ//FWTbiNt6aWKm/66JWHrty8HM1coc1DMpW6AHtguQA=
  on:
    tags: true
    repo: noflo/noflo-component-loader
