language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: OuuEh0a5J3QibJ+87P1a3GSimxGunz/YcB5sfUkZqCn1dX0uCKoTAR/iTlrzqDVOHH6ZvdSy5TISpZgy+JNdYST2O/WR2mvnWYXLy5BcT2QB822CJN4vsw/pVMLd7UKdyz3p95orn4dZuEaMBbQo55Wb+uTyaKO2UKOZtubJGRwr+n9qiXQw+UoK3pIj2QmWHGm8Pur0gTD757IjYN+FsUXNCa41/OHOrYFNUcuPi1xm3h+K3OYtsDo/hKOlghHkJRYOJJvn91acup9pWEkdWU1+WMfFIl5zCLGNciGUU0tJyN6K/R0CBUm8B0AXaxyIuZtb/cGVFV+5TAURXBXARfA9qWU4KUVxjX20VBj+/7DjyO2l7AVGojXMq//JoGbJEJ2ywITte4XoZXT+8qLInJWi8fyNDPmjhFCzaa/RstVzv+acyeUD9fS4Zmh37RqWp5aneQ7/bJDjqrTQjkpWH9VXmlVhI4mPGtNa1xrqHrjEDepL0IxQIUMEdILzNKwetrNSKomcLZzVbaJ62YYWSlVKpgATrqR2fq/FjMIdMwF5UEvUfUlaTW8BuSTdiGiQPAqk6dnocEWYnMCCKrBsD3mQY1/ozauYIjEK8yJUlkIm6hCEmG887LP1kM0a4fCUGBdKbsoScyUpQFA6G2bHYhLVv634Ijq7DMqX45NhqrU=
  on:
    tags: true
    repo: noflo/noflo-component-loader
