language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: Bs5axkwRBGgG1nsoKp98mOUUuiNfRUMTSttPOx76XDYOYLvnKfVvFkQZT9ft/zJ2zLSN03MjpxAsONplUyhWy7vazd9T5u2vvroJqvEE1Mdpe7SMITI/ifuQr/tkzrNeHtVquNLOgrVZpMq8+65cx9V5KGJrnwGTQd3eexmfS1wK4/qkKe8eMSpwUxAqmlv2Kf+i7jFNDumltw9ACrnHsOYESXc5yPUJaE4XHjQnOFVbKYKWWL6UCWcQdad5jX5xKAxTXzJio+E1na/fdQ88jH/xb2buZHszurodzsBaX13akKIYGEutV/ZOZt8U06w2nFCQtfCUS5B0IvfywNo9KjUXI8Kl2BmyNVZtnly7MTOgU9WRRKMuzGshwXuw1GP8aQu6di58/HU6gSbeggK+JmtiRgJLmNyikq4aUCHZ4Cv82ouuN+E6P8p9g4+FrZH842X6jDfMFw2Dsy001c6jPXPSlw0KW0/S0DBefB8FgIZnETppAtqoGxz4/P6FBkfjcG5TDbBBvsPOQwgVinzIOlXrjI1EpuxHopGq/pj+uGscl25k/6KFg9cAngTp2hOMK3iW1mq2Gc9fHk6g95sLFqOxMwD27GPNFaqdEvP/SF8oDIjFIFfQ9sLOHMimhCDREZ5uA+CnevndzZYkMY7owOfIyqAjUX3hpyty5ESdcZE=
  on:
    tags: true
    repo: noflo/noflo-component-loader
