language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: uLuu0HbsOaaQGWLdEFBwjubJDOQyaEpmW2JB23VWxd0lRY6jk5aWaMHxruwjTAUh9Bq7juEpFXR6yiT4On8as6/ueUYaFiCMSro6Lr4MNlW9+XaGvK/epK+kHs9k8ccKivdpenAg9uUoYfKFff/4SVT2ibbojH9EKCOxNEtZYHiQRxbo95+YoDTpipLjhoscla79f/jBIVIWdi6mQLBA0ZTGvcUA6lmicb/Vvndjy+tMlwmlPejZ7YdFfOCcpiZCBoRJ498pKjVPOOGj+a56MXFW2PusJzLQbyZ9fFDsY7S7xmjVF6UholJR5Z5hn48FE1p6bUkh1Ht1lDh+UNnDPJmUNQ3sS6lXcggEIW14IC6AqABfr5SrRUuNhyW42QsE7q8MhnFFMjR6fmn1xzXtk+3VAbVmEkq5aj63aM/R21wBToEDWXm453RpgQEr6utLIkbC6C2PElBbYzPMF6ySYQuPaqpO25/ogdvuVcrVKmukd5LMqWhQw60ReGzzRur476ZZeEOryjHjhzdMumTNrhe2/CXmpKvJXsc2AcD2WDEQEoR5S6adoAgKYb+W4OGBSDTG1DbTFUcerl4AQp/qMBXfID4f/n5E5U8SYQWoZjyvfR9olCtKq0K4uJtaLUTI4qLzrokAkU+ngrPlwd2CfkhueVYBR9CfWDSEmpW3+lM=
  on:
    tags: true
    repo: noflo/noflo-component-loader
