const path = require('path');
const fs = require('fs');

function modulesToData(modules, options) {
  const data = {
    sources: {},
    components: [],
    loaders: [],
    icons: [],
  };

  modules.forEach((module) => {
    if (module.icon) {
      data.icons.push({
        module: module.name,
        icon: module.icon,
      });
    }
    if (module.noflo && module.noflo.loader) {
      const loaderPath = path.resolve(options.baseDir, module.base, module.noflo.loader);
      data.loaders.push(loaderPath);
    }
    if (!module.components) {
      return;
    }
    module.components.forEach((component) => {
      const componentPath = path.resolve(options.baseDir, component.path);
      data.components.push({
        module: module.name,
        name: component.name,
        path: componentPath,
        elementary: component.elementary,
      });
    });
  });

  if (!options.debug) {
    // Debug not enabled, no need to load source files
    return Promise.resolve(data);
  }

  const sourcePromises = data.components
    .filter((component) => component.elementary)
    .map((component) => {
      const p = new Promise((resolve, reject) => {
        fs.readFile(component.path, 'utf-8', (err, source) => {
          if (err) {
            reject(err);
            return;
          }
          let language = 'javascript';
          if (path.extname(component.path) === '.coffee') {
            language = 'coffeescript';
          }
          const fullName = component.module ? `${component.module}/${component.name}` : component.name;
          data.sources[fullName] = {
            language,
            source,
          };
          resolve();
        });
      });
      return p;
    });
  return Promise.all(sourcePromises)
    .then(() => data);
}

function registerIcon(icon) {
  let iconModule = icon.module;
  if (!iconModule) {
    iconModule = null;
  }
  return `loader.setLibraryIcon(${JSON.stringify(iconModule)}, ${JSON.stringify(icon.icon)});`;
}

function registerComponent(component) {
  let componentModule = component.module;
  if (!componentModule) {
    componentModule = null;
  }
  return `loader.registerComponent(${JSON.stringify(componentModule)}, ${JSON.stringify(component.name)}, require(${JSON.stringify(component.path)}));`;
}

function registerLoader(loader) {
  return `loaders.push(require(${JSON.stringify(loader)}));`;
}

function produceLoader(data) {
  return Promise.resolve(`
// File generated by noflo-component-loader on ${new Date().toISOString()}
var baseLoader = require('noflo-component-loader/lib/loader.js');
var sources = ${JSON.stringify(data.sources)};

exports.setSource = function (loader, packageId, name, source, language, callback) {
  baseLoader.setSource(sources, loader, packageId, name, source, language, callback);
};
exports.getSource = function (loader, name, callback) {
  baseLoader.getSource(sources, loader,  name, callback);
}

exports.register = function (loader, callback) {
  ${data.icons.map(registerIcon).join('\n  ')}
  ${data.components.map(registerComponent).join('\n  ')}
  var loaders = [];
  ${data.loaders.map(registerLoader).join('\n  ')}
  baseLoader.registerCustomLoaders(loader, loaders, callback);
};
  `);
}

function serializeLoader(modules, options) {
  return modulesToData(modules, options)
    .then(produceLoader);
}

module.exports = serializeLoader;
